SET @p := (SELECT project_id FROM migration_project WHERE name='바사증권 트레이딩 시스템');
DELETE FROM dependency WHERE project_id=@p;
DELETE FROM certificate WHERE project_id=@p;
DELETE bp FROM backup_plan bp JOIN asset a ON a.asset_id=bp.asset_id WHERE a.project_id=@p;
DELETE i FROM asset_ip i JOIN asset a ON a.asset_id=i.asset_id WHERE a.project_id=@p;
DELETE s FROM asset_software s JOIN asset a ON a.asset_id=s.asset_id WHERE a.project_id=@p;
DELETE FROM asset WHERE project_id=@p;
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'web01','SERVER','WEB','CentOS','7.9.2009'); SET @web:=LAST_INSERT_ID();
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'db01','SERVER','DB','CentOS','7.9.2009'); SET @db:=LAST_INSERT_ID();
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'centos', 'OS', '7.9.2009', '7', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'centos', 'OS', '7.9.2009', '7', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '11.0.22', '11.0', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '11.0.22', '11.0', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.0.33', '8.0', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.0.33', '8.0', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'centos', 'OS', '7.9.2009', '7', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'centos', 'OS', '7.9.2009', '7', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '9.6.1', '9.6', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '9.6.1', '9.6', 'AFTER');
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@web,'172.31.10.11','PRIVATE','AFTER',0);
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@web,'203.0.113.50','PUBLIC','AFTER',0);
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@db,'172.31.20.21','PRIVATE','AFTER',0);
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2026-11-05','BEFORE');
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2026-11-05','AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'BEFORE');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@db,'2026-09-30',0,0,'BEFORE');
INSERT INTO dependency (project_id,from_asset_id,to_asset_id,target_address,target_port,protocol) VALUES (@p,@web,@db,'203.0.113.60',3306,'JDBC');

SET @p := (SELECT project_id FROM migration_project WHERE name='라마마트 물류 플랫폼');
DELETE FROM dependency WHERE project_id=@p;
DELETE FROM certificate WHERE project_id=@p;
DELETE bp FROM backup_plan bp JOIN asset a ON a.asset_id=bp.asset_id WHERE a.project_id=@p;
DELETE i FROM asset_ip i JOIN asset a ON a.asset_id=i.asset_id WHERE a.project_id=@p;
DELETE s FROM asset_software s JOIN asset a ON a.asset_id=s.asset_id WHERE a.project_id=@p;
DELETE FROM asset WHERE project_id=@p;
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'web01','SERVER','WEB','Rocky Linux','9.4'); SET @web:=LAST_INSERT_ID();
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'db01','SERVER','DB','Rocky Linux','9.4'); SET @db:=LAST_INSERT_ID();
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'AFTER');
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@web,'172.31.10.11','PRIVATE','AFTER',0);
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@db,'172.31.20.21','PRIVATE','AFTER',0);
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2027-12-01','BEFORE');
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2027-12-01','AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'BEFORE');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@db,'2026-10-06',0,1,'BEFORE');
INSERT INTO dependency (project_id,from_asset_id,to_asset_id,target_address,target_port,protocol) VALUES (@p,@web,@db,'10.20.0.21',3306,'JDBC');

SET @p := (SELECT project_id FROM migration_project WHERE name='차타병원 EMR');
DELETE FROM dependency WHERE project_id=@p;
DELETE FROM certificate WHERE project_id=@p;
DELETE bp FROM backup_plan bp JOIN asset a ON a.asset_id=bp.asset_id WHERE a.project_id=@p;
DELETE i FROM asset_ip i JOIN asset a ON a.asset_id=i.asset_id WHERE a.project_id=@p;
DELETE s FROM asset_software s JOIN asset a ON a.asset_id=s.asset_id WHERE a.project_id=@p;
DELETE FROM asset WHERE project_id=@p;
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'web01','SERVER','WEB','Rocky Linux','9.4'); SET @web:=LAST_INSERT_ID();
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'db01','SERVER','DB','Rocky Linux','9.4'); SET @db:=LAST_INSERT_ID();
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '11.0.24', '11', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'AFTER');
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@web,'172.31.10.11','PRIVATE','AFTER',0);
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@db,'172.31.20.21','PRIVATE','AFTER',0);
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2027-08-01','BEFORE');
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2027-08-01','AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'BEFORE');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@db,'2026-10-06',0,0,'BEFORE');
INSERT INTO dependency (project_id,from_asset_id,to_asset_id,target_address,target_port,protocol) VALUES (@p,@web,@db,'10.30.0.21',3306,'JDBC');

SET @p := (SELECT project_id FROM migration_project WHERE name='아자카드 결제 게이트웨이');
DELETE FROM dependency WHERE project_id=@p;
DELETE FROM certificate WHERE project_id=@p;
DELETE bp FROM backup_plan bp JOIN asset a ON a.asset_id=bp.asset_id WHERE a.project_id=@p;
DELETE i FROM asset_ip i JOIN asset a ON a.asset_id=i.asset_id WHERE a.project_id=@p;
DELETE s FROM asset_software s JOIN asset a ON a.asset_id=s.asset_id WHERE a.project_id=@p;
DELETE FROM asset WHERE project_id=@p;
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'web01','SERVER','WEB','Rocky Linux','9.4'); SET @web:=LAST_INSERT_ID();
INSERT INTO asset (project_id,name,asset_type,role,os_name,os_version) VALUES (@p,'db01','SERVER','DB','Rocky Linux','9.4'); SET @db:=LAST_INSERT_ID();
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'tomcat', 'WAS', '10.1.28', '10.1', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '17.0.12', '17', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'java', 'RUNTIME', '17.0.12', '17', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@web, 'mysql-connector-j', 'DRIVER', '8.4.0', '8.4', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'rocky-linux', 'OS', '9.4', '9', 'AFTER');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'BEFORE');
INSERT INTO asset_software (asset_id, product, role, version, release_line, phase) VALUES (@db, 'mysql', 'DB', '8.4.3', '8.4', 'AFTER');
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@web,'172.31.10.11','PRIVATE','AFTER',0);
INSERT INTO asset_ip (asset_id,address,ip_type,phase,ext_whitelisted) VALUES (@db,'172.31.20.21','PRIVATE','AFTER',0);
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2028-03-01','BEFORE');
INSERT INTO certificate (project_id,domain,issuer,not_after,phase) VALUES (@p,'svc.example.com','Lets Encrypt R3','2028-03-01','AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'BEFORE');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@web,'2026-10-06',1,1,'AFTER');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@db,'2026-10-07',1,1,'BEFORE');
INSERT INTO backup_plan (asset_id,last_backup_at,restore_tested,offsite,phase) VALUES (@db,'2026-10-07',1,1,'AFTER');
INSERT INTO dependency (project_id,from_asset_id,to_asset_id,target_address,target_port,protocol) VALUES (@p,@web,@db,'10.40.0.21',3306,'JDBC');

